#ifndef SERVERFILES_GLOBAL_H
#define SERVERFILES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERVERFILES_LIBRARY)
#  define SERVERFILESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERVERFILESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERVERFILES_GLOBAL_H
